# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  AWS_PROFILE: lab

tasks:
  default:
    silent: true
    cmds:
      - task -l

  deploy:
    desc: Deploy job hunter infrastructure
    dir: terraform
    silent: true
    cmds:
      - terraform init -backend-config=backend.hcl
      - terraform apply -auto-approve

  destroy:
    desc: Destroy job hunter infrastructure
    dir: terraform
    silent: true
    cmds:
      - terraform destroy -auto-approve

  seed:
    desc: Seed the DynamoDB companies table from companies/companies.json
    silent: true
    cmds:
      - |
        uv run python -c "
        import json, boto3
        data = json.load(open('companies/companies.json'))
        table = boto3.resource('dynamodb').Table('job-hunter-companies')
        for item in data:
            table.put_item(Item=item)
            print(f'Seeded: {item[\"company_name\"]}')
        print(f'Done. {len(data)} companies seeded.')
        "
